{
    "failPipeline": true,
    "instructions": "{{ var "text" ?: "Is it okay to proceed?" }}",
    "judgmentInputs": [
        {
            "value": "hello"
        },
        {
            "value": "goodbye"
        }
    ],
    "judgmentInputs": [],
    "name": "Manual Judgment",
    "notifications": [],
    "refId": "{{ var "refId" ?: "1" }}",
    "requisiteStageRefIds": {{ var "requisiteStageRefIds" ?: [] }},
    "type": "manualJudgment"
}
